version: '2' #docker-composeのバージョンを指定
services:
    bbs:
        build: . #Dockerfileをビルド
        ports:
            - "7080:8080" #ポート9000番の開放
        links:
            - "db:db" #dbとつなげる
        privileged: true
        tty: true
        command: /sbin/init

networks:
  default:
    external:
      name: onyx